
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ynab_dbt_transforms'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ynab_dbt_transforms'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
analysis-paths: ["analyses"]
docs-paths: ["docs"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +grants:
    select: ['"READER"']
  ynab_dbt_transforms:
    staging:
      +materialized: view
      +schema: staging
      +tags: staging
      +docs:
        node_color: "#cd7f32"  # bronze hex
    translate:
      +materialized: view
      +schema: translate
      +tags: translate
      +docs:
        node_color: "silver"
    mart:
      +materialized: table
      +schema: mart
      +tags: mart
      +docs:
        node_color: "gold"

on-run-end:
  - '{% for schema in schemas %}grant usage on schema {{ schema }} to "READER";{% endfor %}'