version: 2

sources:
  - name: ynab_budget
    description: "YNAB budget data in local postgresql database"
    database: dev  
    schema: raw
    tables:
      - name: transactions
        description: "Transactions data for main budget in YNAB."
        columns:
          - name: id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: amount
            description: "Transaction amount (in cents)"
            tests:
              - not_null

      - name: transactions_subtransactions
        description: "Sub-transactions data for main budget in YNAB for transactions that have been split."
        columns:
          - name: id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: amount
            description: "Transaction amount (in cents)"
            tests:
              - not_null
        
      - name: categories_categories
        description: "Main category groups for main budget in YNAB."
        columns:
          - name: id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: name
            description: "Category name"
            tests:
              - unique
              - not_null
          - name: category_group_id
            description: "ID of Category Group"
            tests:
              - not_null
          - name: category_group_name
            description: "Category Group Name"
            tests:
              - not_null

      - name: categories
        description: "Granular categories for main budget in YNAB."
        columns:
          - name: id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: name
            description: "Category group name"
            tests:
              - unique
              - not_null
