select
    id as transaction_id,
    to_date(date, 'yyyy-mm-dd') as date,
    (amount / 1000) as amount,
    category_id,
    category_name,
    payee_id,
    payee_name,
    account_id,
    account_name,
    debt_transaction_type,
    memo,
    cleared,
    approved,
    flag_color,
    deleted,
    import_payee_name,
    import_payee_name_original,
    import_id,
    transfer_account_id,
    transfer_transaction_id,
    matched_transaction_id
from {{ source('ynab_budget', 'transactions_data_transactions') }}
